apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy54
  labels:
    app: autodeploy54
  namespace: namespace-workflow-1714395846350
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy54
  template:
    metadata:
      labels:
        app: autodeploy54
    spec:
      containers:
        - name: autodeploy54
          image: acrworkflow1714397388452.azurecr.io/image-workflow-1714397388452:latest
          ports:
            - containerPort: 5000